let element_banana = document.getElementById('banana');
element_banana.style.color = '#ffff00';
element_banana.style.backgroundColor = '#666666';
let element_apple = document.getElementById('apple');
element_apple.style.color = '#33ff33';
element_apple.style.backgroundColor = '#666666';
let element_strawberry = document.getElementById('strawberry');
element_strawberry.style.color = '#ff0000';
element_strawberry.style.backgroundColor = '#666666';
